# Generated by Django 3.0.4 on 2020-03-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_chapters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapters',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='chapters',
            old_name='name',
            new_name='chapter_name',
        ),
    ]
