# Generated by Django 3.0.4 on 2020-03-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='books',
            field=models.ManyToManyField(related_name='books', to='restapi.Books'),
        ),
    ]
