# Generated by Django 3.0.4 on 2020-03-17 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20200317_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='books',
            field=models.ManyToManyField(to='restapi.Books'),
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Books')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Characters')),
            ],
        ),
    ]
