# Generated by Django 3.0.4 on 2020-03-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20200310_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapters',
            old_name='book_id',
            new_name='book',
        ),
    ]
